[tools]
rust = [
    {
        version = "stable",
        components = ["rust-src"],
    },
    {
        version = "nightly",
        components = ["rust-src"],
    },
]

# Rust 工具
"cargo:cargo-nextest" = {
    version = "latest",
    depends = ["rust"],
}

"cargo:cargo-binstall" = {
    version = "latest",
    depends = ["rust"],
}
