[settings]
minimum_release_age = "1h"

[tools]
node = { version = "latest" }
pnpm = {
    version = "latest",
    depends = ["node"],
}
yarn = {
    version = "latest",
    depends = ["node"],
}

python = "latest"
rust = [
    {
        version = "stable",
        components = ["rust-src"],
    },
    {
        version = "nightly",
        components = ["rust-src"],
    },
]

# AI 工具
"npm:@openai/codex" = {
    version = "latest",
    depends = ["node"],
}
"aqua:anomalyco/opencode" = {
    version = "latest",
}
"aqua:google-antigravity/antigravity-cli" = {
    version = "latest",
}
"aqua:anthropics/claude-code" = {
    version = "latest",
}

# Rust 工具
"cargo:cargo-nextest" = {
    version = "latest",
    depends = ["rust"],
}

"cargo:cargo-binstall" = {
    version = "latest",
    depends = ["rust"],
}

# 实用工具
jq = "latest"
ripgrep = "latest"
gh = "latest"
