[settings.cargo]
binstall = true
binstall_native = true
binstall_quickinstall = true

[tools]
rust = {
    version = "stable",
    components = ["rust-src"],
}

# Rust 工具
cargo-binstall = {
    version = "latest",
}

sccache = {
    version = "latest",
}

"cargo:cargo-nextest" = {
    version = "latest",
    depends = ["cargo-binstall"],
}

"cargo:cargo-sweep" = {
    version = "latest",
    depends = ["cargo-binstall"],
}

