[settings]
minimum_release_age = "1h"
yes = true

[tools]
python = "latest"

node = { version = "latest" }
pnpm = {
    version = "latest",
    depends = ["node"],
}
yarn = {
    version = "latest",
    depends = ["node"],
}

# AI 工具
"npm:@openai/codex" = {
    version = "latest",
    depends = ["node"],
}
"aqua:anomalyco/opencode" = {
    version = "latest",
}
"aqua:google-antigravity/antigravity-cli" = {
    version = "latest",
}
"aqua:anthropics/claude-code" = {
    version = "latest",
}

# 实用工具
direnv = "latest"
jq = "latest"
ripgrep = "latest"
gh = "latest"
