[settings.cargo]
binstall = true
binstall_native = true
binstall_quickinstall = true

[tools]
rust = {
    version = "stable",
    components = ["rust-src"],
    targets = ["wasm32-unknown-unknown"],
}

# WebAssembly 工具
"cargo:wasmi_cli" = {
    version = "latest",
    depends = ["rust"],
}
"cargo:wasm-pack" = {
    version = "latest",
    depends = ["rust"],
}
"cargo:wasm-bindgen-cli" = {
    version = "latest",
    depends = ["rust"],
}
